language: python
python:
  - '3.6'
  - '3.6-dev'
  - '3.7-dev'
  - 'nightly'

install:
  - pip install .

script: python setup.py test

matrix:
  allow_failures:
    - python: '3.6-dev'
    - python: '3.7-dev'
    - python: 'nightly'
